services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - 3306
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_pass
      - db_user_name
      - db_user_pass

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - 9000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/srv/www/wordpress
    secrets:
      - db_root_pass
      - db_user_name
      - db_user_pass
      - wp_adm_user
      - wp_adm_email
      - wp_adm_pass
      - wp_user_name
      - wp_user_email
      - wp_user_pass

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
    - .env
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/srv/www/wordpress
      

volumes:

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/fernacar/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/fernacar/data/wordpress
      o: bind


secrets:

  db_root_pass:
    file: ../secrets/db_root_pass.txt

  db_user_name:
    file: ../secrets/db_user_name.txt

  db_user_pass:
    file: ../secrets/db_user_pass.txt

  wp_adm_user:
    file: ../secrets/wp_adm_user.txt

  wp_adm_email:
    file: ../secrets/wp_adm_email.txt

  wp_adm_pass:
    file: ../secrets/wp_adm_pass.txt

  wp_user_name:
    file: ../secrets/wp_user_name.txt

  wp_user_email:
    file: ../secrets/wp_user_email.txt

  wp_user_pass:
    file: ../secrets/wp_user_pass.txt


networks:

  inception:
    driver: bridge
